[package]
name = "xbox"
version = "0.1.0"
authors = ["Joel Kuzmarski <leoj3n@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.7.2"
